# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMasonry' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMasonry
  pod 'Masonry'
  target 'TestMasonryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestMasonryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
